export const students = [
  {
    id: 1,
    name: "Jolie Joie",
    semester: "Semester 5",
    points: 100000,
    image: "https://i.pravatar.cc/150?img=32",
  },
  {
    id: 2,
    name: "Brian Ngo",
    semester: "Semester 6",
    points: 85000,
    image: "https://i.pravatar.cc/150?img=12",
  },
  {
    id: 3,
    name: "David Do",
    semester: "Semester 4",
    points: 72000,
    image: "https://i.pravatar.cc/150?img=22",
  },
  {
    id: 4,
    name: "Henrietta O'Connell",
    semester: "Semester 3",
    points: 68000,
    image: "https://i.pravatar.cc/150?img=45",
  },
  {
    id: 5,
    name: "Darrel Bins",
    semester: "Semester 2",
    points: 64000,
    image: "https://i.pravatar.cc/150?img=56",
  },
  {
    id: 6,
    name: "Sophia Martinez",
    semester: "Semester 1",
    points: 61000,
    image: "https://i.pravatar.cc/150?img=60",
  },
  {
    id: 7,
    name: "Liam Anderson",
    semester: "Semester 6",
    points: 59000,
    image: "https://i.pravatar.cc/150?img=14",
  },
  {
    id: 8,
    name: "Emily Chen",
    semester: "Semester 4",
    points: 56000,
    image: "https://i.pravatar.cc/150?img=47",
  },
  {
    id: 9,
    name: "Noah Patel",
    semester: "Semester 5",
    points: 53000,
    image: "https://i.pravatar.cc/150?img=18",
  },
  {
    id: 10,
    name: "Ava Williams",
    semester: "Semester 3",
    points: 50000,
    image: "https://i.pravatar.cc/150?img=33",
  },
];
